{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skeinrank.secretName" . }}
  labels:
    {{- include "skeinrank.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.keys.databaseUrl }}: {{ .Values.secrets.databaseUrl | quote }}
  {{ .Values.secrets.keys.adminPassword }}: {{ .Values.secrets.adminPassword | quote }}
  {{ .Values.secrets.keys.celeryBrokerUrl }}: {{ .Values.secrets.celeryBrokerUrl | quote }}
  {{ .Values.secrets.keys.elasticsearchUsername }}: {{ .Values.secrets.elasticsearchUsername | quote }}
  {{ .Values.secrets.keys.elasticsearchPassword }}: {{ .Values.secrets.elasticsearchPassword | quote }}
  {{ .Values.secrets.keys.elasticsearchApiKey }}: {{ .Values.secrets.elasticsearchApiKey | quote }}
{{- end }}
