"""Terminology governance storage primitives for SkeinRank.

This package is the platform foundation for future Postgres-backed terminology
management. Runtime extraction still uses exported snapshots; the database is a
control-plane source of truth.
"""

from .cli import (
    GovernanceCliError,
    add_alias,
    add_term,
    build_snapshot,
    create_profile,
    export_snapshot,
    get_profile,
    list_terms,
    resolve_database_url,
)
from .db import Base, create_all, create_governance_engine, create_session_factory
from .models import (
    ACTIVE_STATUS,
    ALIAS_STATUSES,
    API_TOKEN_OWNER_TYPES,
    ELASTICSEARCH_BINDING_MODES,
    ELASTICSEARCH_BINDING_PROVIDERS,
    ELASTICSEARCH_BINDING_WRITE_STRATEGIES,
    ELASTICSEARCH_ENRICHMENT_JOB_STATUSES,
    SNAPSHOT_STATUSES,
    STOP_LIST_TARGETS,
    SUGGESTION_SOURCES,
    SUGGESTION_STATUSES,
    SUGGESTION_TYPES,
    TERM_STATUSES,
    USER_ROLES,
    USER_STATUSES,
    AuditEvent,
    CanonicalTerm,
    ElasticsearchBinding,
    ElasticsearchEnrichmentJob,
    GovernanceApiToken,
    GovernanceAuthToken,
    GovernanceGlobalStopListEntry,
    GovernanceServiceAccount,
    GovernanceStopListEntry,
    GovernanceSuggestion,
    GovernanceUser,
    ProfileSnapshot,
    TermAlias,
    TerminologyProfile,
    normalize_profile_name,
    normalize_value,
)

__all__ = [
    "GovernanceCliError",
    "add_alias",
    "add_term",
    "build_snapshot",
    "create_profile",
    "export_snapshot",
    "get_profile",
    "list_terms",
    "resolve_database_url",
    "ACTIVE_STATUS",
    "ALIAS_STATUSES",
    "API_TOKEN_OWNER_TYPES",
    "ELASTICSEARCH_BINDING_MODES",
    "ELASTICSEARCH_BINDING_PROVIDERS",
    "ELASTICSEARCH_BINDING_WRITE_STRATEGIES",
    "ELASTICSEARCH_ENRICHMENT_JOB_STATUSES",
    "Base",
    "AuditEvent",
    "CanonicalTerm",
    "GovernanceApiToken",
    "ElasticsearchBinding",
    "ElasticsearchEnrichmentJob",
    "GovernanceAuthToken",
    "GovernanceGlobalStopListEntry",
    "GovernanceServiceAccount",
    "GovernanceStopListEntry",
    "GovernanceSuggestion",
    "GovernanceUser",
    "ProfileSnapshot",
    "SNAPSHOT_STATUSES",
    "SUGGESTION_SOURCES",
    "SUGGESTION_STATUSES",
    "SUGGESTION_TYPES",
    "STOP_LIST_TARGETS",
    "TERM_STATUSES",
    "USER_ROLES",
    "USER_STATUSES",
    "TermAlias",
    "TerminologyProfile",
    "create_all",
    "create_governance_engine",
    "create_session_factory",
    "normalize_profile_name",
    "normalize_value",
]
