"""SkeinRank public API.

Only symbols exported from this module are considered **stable public API**.
Internal modules may change without notice.
"""

from .app.engine import RerankEngine, rerank, rerank_many, score
from .app.profiles import get_profile, list_profiles, validate_profile
from .attributes import (
    AttributeEvidence,
    AttributeModelAdapters,
    AttributePack,
    AttributePassport,
    AttributeProfile,
    AttributeSlot,
    AttributeSnapshot,
    AttributeStageStatus,
    AttributeTrace,
    ExtractedAttribute,
    FailingAdapter,
    ModelCandidate,
    ProfileValidationIssue,
    ProfileValidationReport,
    StaticE5Adapter,
    StaticGLiNERAdapter,
    StaticKeyBERTAdapter,
    build_attribute_profile,
    build_attribute_profile_template,
    enrich_documents,
    enrich_jsonl,
    enrich_texts,
    evaluate_demo_queries,
    extract_attributes,
    get_attribute_profile,
    list_attribute_profiles,
    load_attribute_profile,
    load_jsonl,
    validate_attribute_profile,
    write_attribute_profile_template,
    write_jsonl,
)
from .documents import (
    DocumentExtractionError,
    DocumentExtractionResult,
    DocumentText,
    extract_document_text,
    extract_terms_from_document,
    load_document_text,
)
from .domain.errors import ContractError, ModelUnavailable, SkeinRankError
from .domain.types import (
    Candidate,
    RankedItem,
    RequestPassport,
    RerankRequest,
    RerankResult,
    ScoreResult,
)
from .sdk import (
    CanonicalizedText,
    Dictionary,
    DictionaryAlias,
    DictionaryStopListEntry,
    DictionaryTerm,
    DictionaryValidationIssue,
    DictionaryValidationReport,
    ExtractionResult,
    TermMatch,
    canonicalize_text,
    extract_terms,
    load_dictionary,
    validate_dictionary,
)

__all__ = [
    "RerankEngine",
    "rerank",
    "rerank_many",
    "score",
    "list_profiles",
    "get_profile",
    "validate_profile",
    "Candidate",
    "RerankRequest",
    "RankedItem",
    "RerankResult",
    "ScoreResult",
    "RequestPassport",
    "extract_attributes",
    "get_attribute_profile",
    "list_attribute_profiles",
    "build_attribute_profile",
    "load_attribute_profile",
    "write_attribute_profile_template",
    "build_attribute_profile_template",
    "validate_attribute_profile",
    "ProfileValidationIssue",
    "ProfileValidationReport",
    "load_jsonl",
    "write_jsonl",
    "enrich_documents",
    "enrich_jsonl",
    "enrich_texts",
    "evaluate_demo_queries",
    "AttributeModelAdapters",
    "ModelCandidate",
    "StaticGLiNERAdapter",
    "StaticE5Adapter",
    "StaticKeyBERTAdapter",
    "FailingAdapter",
    "AttributeSlot",
    "AttributeEvidence",
    "ExtractedAttribute",
    "AttributeTrace",
    "AttributeProfile",
    "AttributeSnapshot",
    "AttributeStageStatus",
    "AttributePassport",
    "AttributePack",
    "DocumentText",
    "DocumentExtractionResult",
    "DocumentExtractionError",
    "load_document_text",
    "extract_document_text",
    "extract_terms_from_document",
    "Dictionary",
    "DictionaryAlias",
    "DictionaryTerm",
    "DictionaryStopListEntry",
    "DictionaryValidationIssue",
    "DictionaryValidationReport",
    "TermMatch",
    "ExtractionResult",
    "CanonicalizedText",
    "load_dictionary",
    "validate_dictionary",
    "extract_terms",
    "canonicalize_text",
    "SkeinRankError",
    "ContractError",
    "ModelUnavailable",
]

__version__ = "0.0.16"
