apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: skeinrank-runtime-artifact
  namespace: flux-system
spec:
  interval: 1m
  path: ./examples/gitops-delivery/runtime-artifact
  prune: true
  sourceRef:
    kind: GitRepository
    name: skeinrank-runtime-artifacts
  targetNamespace: search-runtime
  wait: true
  timeout: 2m
