apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
configMapGenerator:
  - name: skeinrank-runtime-snapshot
    files:
      - runtime-snapshot.json=runtime-snapshot.example.json
generatorOptions:
  disableNameSuffixHash: false
